# name: main
# ## Triggers the workflow on when there is a push, or 
# ## pull request on the main branch
# on: push 
# jobs:
#   job1:
#     ## The type of runner that the job will run on
#     runs-on: windows-latest 
#     env:
#       ## Environment variable
#       API_KEY: XXXXXXXXXXXX    
#     steps:
#       - name: step 1
#         ## Reference your environment variables
#         # run: echo "The API key is:${{env.API_KEY}}"  
#         run: echo "The API key is:$API_KEY"  

#   job2:
#     runs-on: windows-latest
#     steps:
#       - name: step 1
#         ## Another way reference your environment variables
#         run: echo "The API key is:$API_KEY"   

name: main
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: push 

jobs:
  job1:
    ## The type of runner that the job will run on
    runs-on: windows-latest 
    steps:
     - name: step 1
     env:
    ## Environment variable for step 1
      API_KEY: XXXXXXXXXXXX    
        ## Reference your environment variables
        run: echo "The API key is:${{env.API_KEY}}"   
      - name: step 2
        ## Reference your environment variables
        run: echo "The API key is:${{env.API_KEY}}" 
        